spring.application.name=auth-api

# Postgre SQL - Connection
spring.datasource.url=${POSTGRE_SQL_URI}
spring.datasource.username=${POSTGRE_SQL_USER}
spring.datasource.password=${POSTGRE_SQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool (Hikari)
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.data-source-properties.tcpKeepAlive=true

# Security Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Alexa OAuth2 Configuration (Common)
alexa.oauth.client-id=${ALEXA_OAUTH_CLIENT_ID:alexa-skill-client}
alexa.oauth.access-token-expiration-seconds=${ALEXA_OAUTH_ACCESS_TOKEN_EXPIRATION_SECONDS:3600}
alexa.oauth.code-ttl-seconds=${ALEXA_OAUTH_CODE_TTL_SECONDS:300}