# Configuración para Ambiente de Producción
management.endpoints.web.exposure.include=health,info

# Base de Datos y JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

server.forward-headers-strategy=framework

# LOGGING
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=OFF

# Seguridad y CORS
app.security.allowed-origins=${ALLOWED_ORIGINS}

# Alexa OAuth2
alexa.oauth.client-secret=${ALEXA_OAUTH_CLIENT_SECRET}
