# Configuración para Ambiente de Desarrollo
server.port=${SERVER_PORT_BACK:8083}

# Base de Datos y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seguridad y CORS
app.security.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000}

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Alexa OAuth2
alexa.oauth.client-secret=${ALEXA_OAUTH_CLIENT_SECRET:change-me}
