# Configuración para Ambiente de Desarrollo
server.port=${SERVER_PORT_BACK:8083}

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ----------------------------------------
# DATABASE CONNECTION (Drivers and Base Hikari)
# ----------------------------------------
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# ----------------------------------------
# LOGGING
# ----------------------------------------
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
